# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Guest.create({:name => "Alessandro", :email => "alessandrovitale@libero.it", :gift => nil})
Guest.create({:name => "Alicia Sanchez-Mora", :email => "aliciasmm82@gmail.com", :gift => nil})
Guest.create({:name => "Almut Eisenmann", :email => "Almut.Eisenmann@t-online.de", :gift => nil})
Guest.create({:name => "Amy Kinsella", :email => "amykinsella22@gmail.com", :gift => nil})
Guest.create({:name => "Andrea Tillmanns", :email => "andrea@textdenker.de", :gift => nil})
Guest.create({:name => "Andreh Krikourian", :email => "andreh.krikourian@googlemail.com", :gift => nil})
Guest.create({:name => "Angela Poth", :email => "angela.poth@gmx.de", :gift => nil})
Guest.create({:name => "Ann-Cathrin Biermann", :email => "ann-cathrin.biermann@gmx.de", :gift => nil})
Guest.create({:name => "Anna Bosca", :email => "annabosca@gmail.com", :gift => nil})
Guest.create({:name => "Anne Allmeling", :email => "anne@allmeling.de", :gift => nil})
Guest.create({:name => "Anne Koop", :email => "anne.koop@web.de", :gift => nil})
Guest.create({:name => "Annette Dederichs", :email => "annette.dederichs@zhv.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Aramazd", :email => "Aramazd@gmx.de", :gift => nil})
Guest.create({:name => "Arnd Gottschalk", :email => "gottschalk@fh-aachen.de", :gift => nil})
Guest.create({:name => "Arndt Allmeling", :email => "arndt@allmeling.de", :gift => nil})
Guest.create({:name => "Astrid Nisch", :email => "examiniertekaffeeschubse@hotmail.de", :gift => nil})
Guest.create({:name => "Barbara Babette", :email => "barbarababette@hotmail.com", :gift => nil})
Guest.create({:name => "Barbara Seihs", :email => "barbara.seihs@web.de", :gift => nil})
Guest.create({:name => "Barbara Vogel", :email => "Barbara_Vogel@gmx.de", :gift => nil})
Guest.create({:name => "Bayram Aslan", :email => "bay_aslan@gmx.de", :gift => nil})
Guest.create({:name => "Benjamin Buch", :email => "benni.buch@gmx.de", :gift => nil})
Guest.create({:name => "Benjamin Nagengast", :email => "Benjamin.Nagengast@gmx.de", :gift => nil})
Guest.create({:name => "Benno Zimmermann", :email => "benno.zimmermann@gmx.de", :gift => nil})
Guest.create({:name => "Berna Rasche-Schürmann", :email => "Berna.Rasche@gmx.de", :gift => nil})
Guest.create({:name => "Bernadette Neustein", :email => "bernadette.neustein@gmx.de", :gift => nil})
Guest.create({:name => "Birte Frischemeier", :email => "birte.frischemeier@googlemail.com", :gift => nil})
Guest.create({:name => "Birthe Vogel", :email => "birthe-vogel@gmx.de", :gift => nil})
Guest.create({:name => "Carina Hahn", :email => "carinchen1@web.de", :gift => nil})
Guest.create({:name => "Cassia Fresemann", :email => "cassiafresemann@aol.com", :gift => nil})
Guest.create({:name => "Christian Decker", :email => "Decker.Chr@googlemail.com", :gift => nil})
Guest.create({:name => "Christian Gass", :email => "BigDwarf@web.de", :gift => nil})
Guest.create({:name => "Christian Ritter", :email => "C.Ritter@diedrucksache.de", :gift => nil})
Guest.create({:name => "Christian Vedder Fraunhofer ILT", :email => "mail@christianvedder.de", :gift => nil})
Guest.create({:name => "Christina Hamacher", :email => "tina.hamacher@gmx.de", :gift => nil})
Guest.create({:name => "Christina Heinrichs", :email => "tina@die-heinrichs.net", :gift => nil})
Guest.create({:name => "Christoph Depping", :email => "christoph.depping@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Christoph Hammer", :email => "mr.christal@gmx.net", :gift => nil})
Guest.create({:name => "Christoph Kozik", :email => "christoph.kozik@ita.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Claas Tatje", :email => "mail@claastatje.de", :gift => nil})
Guest.create({:name => "Claudia Schwartz", :email => "scratchthepitch@web.de", :gift => nil})
Guest.create({:name => "Cornelia Driesen", :email => "cornelia.driesen@gmx.de", :gift => nil})
Guest.create({:name => "cubcom | jörg carabin", :email => "jc@cub-com.de", :gift => nil})
Guest.create({:name => "Daniel Fuerstenwerth", :email => "daniel.fuerstenwerth@googlemail.com", :gift => nil})
Guest.create({:name => "Daniel Kroh", :email => "danielkroh@web.de", :gift => nil})
Guest.create({:name => "Daniela Driesen", :email => "danieladriesen@web.de", :gift => nil})
Guest.create({:name => "Daniela Ewers", :email => "daniela.ewers@googlemail.com", :gift => nil})
Guest.create({:name => "Daniela Rodtheut", :email => "Daniela2612@gmx.net", :gift => nil})
Guest.create({:name => "Daniela Vossenkaul", :email => "daniela_vossenkaul@gmx.de", :gift => nil})
Guest.create({:name => "Dennis Brandt", :email => "dennis.brandt@gmx.de", :gift => nil})
Guest.create({:name => "Dennis Könißer", :email => "dennis.koenisser@gmail.com", :gift => nil})
Guest.create({:name => "Dirk Horsten", :email => "dirk.horsten@gmx.de", :gift => nil})
Guest.create({:name => "Dirk Schroeder", :email => "shred@gmx.de", :gift => nil})
Guest.create({:name => "Edvard Krikourian", :email => "info@projektelf.de", :gift => nil})
Guest.create({:name => "Elettra", :email => "elettra.86@hotmail.it", :gift => nil})
Guest.create({:name => "Elisabeth Moog", :email => "elisabeth.moog@gmail.com", :gift => nil})
Guest.create({:name => "Elisenda Martínez Casaldàliga", :email => "elipsenda@hotmail.com", :gift => nil})
Guest.create({:name => "Eva Bergrath", :email => "sweetorange11@hotmail.com", :gift => nil})
Guest.create({:name => "Felix Allmendinger", :email => "allmendinger@igm.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Felixine Siegmund", :email => "sf.sunflower@gmx.de", :gift => nil})
Guest.create({:name => "Frank Frost", :email => "frankfrost@gmx.li", :gift => nil})
Guest.create({:name => "Frauke Manninga", :email => "frau.mann@gmx.de", :gift => nil})
Guest.create({:name => "Gabi Lukomski", :email => "gl@backhausbuch.de", :gift => nil})
Guest.create({:name => "Germain Hadasch", :email => "lichtographen@googlemail.com", :gift => nil})
Guest.create({:name => "Guido Holz", :email => "guido@sportograf.de", :gift => nil})
Guest.create({:name => "Hacky Hackhausen", :email => "mail@hackyhackhausen.de", :gift => nil})
Guest.create({:name => "Hiltrud Kliesch", :email => "Hiltrud.Kliesch@inform-ac.com", :gift => nil})
Guest.create({:name => "Huda Husein", :email => "hudahusein@hotmail.de", :gift => nil})
Guest.create({:name => "Ibo Ibbeken", :email => "ibo.ibbeken@gmx.de", :gift => nil})
Guest.create({:name => "Ilka Reuter", :email => "winnitwo@gmail.com", :gift => nil})
Guest.create({:name => "Ina Tatje", :email => "inatatje@gmx.de", :gift => nil})
Guest.create({:name => "Ingrid Cobos", :email => "ingcolo@hotmail.com", :gift => nil})
Guest.create({:name => "Iris Tatje", :email => "Iris.Tatje@googlemail.com", :gift => nil})
Guest.create({:name => "Isabell Moll", :email => "isabell_moll@web.de", :gift => nil})
Guest.create({:name => "Ivesa Vogel", :email => "ivesa.vogel@googlemail.com", :gift => nil})
Guest.create({:name => "Izabella Krikourian", :email => "iza46@op.pl", :gift => nil})
Guest.create({:name => "Jan Benzenberg", :email => "jan@benzenberg.de", :gift => nil})
Guest.create({:name => "Jan Köhler", :email => "schaeng@gmx.de", :gift => nil})
Guest.create({:name => "Jenni Kielas", :email => "jenni.kielas@gmail.com", :gift => nil})
Guest.create({:name => "Jens Hadeler", :email => "jenne@treuenfeld.de", :gift => nil})
Guest.create({:name => "Joana Brückner", :email => "joanabrueckner@yahoo.de", :gift => nil})
Guest.create({:name => "Jochen Wilms", :email => "jochen@ausfuehrer.de", :gift => nil})
Guest.create({:name => "Johanna Holsten", :email => "Johanna.Holsten@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Johanna Theiß", :email => "johanna.theiss@theiss-multimedia.de", :gift => nil})
Guest.create({:name => "Joleen", :email => "joleen.boehmert@arcor.de", :gift => nil})
Guest.create({:name => "Jonathan Rathsam", :email => "jrathsam@gmail.com", :gift => nil})
Guest.create({:name => "Jörg Mihm", :email => "joerg.mihm@online.de", :gift => nil})
Guest.create({:name => "Jost Hinrich Allmeling", :email => "jost@allmeling.de", :gift => nil})
Guest.create({:name => "Juan Medina", :email => "info@medina-design.de", :gift => nil})
Guest.create({:name => "Judith Fothen", :email => "judith.fothen@gmail.com", :gift => nil})
Guest.create({:name => "Juxi Leitner", :email => "juxi.leitner@gmail.com", :gift => nil})
Guest.create({:name => "Karina Kaliwoda", :email => "kkaliwoda@gmx.de", :gift => nil})
Guest.create({:name => "Katharina Krämer", :email => "lieblingsbiene@googlemail.com", :gift => nil})
Guest.create({:name => "Katja Kraemer", :email => "katja.kraemer@gmail.com", :gift => nil})
Guest.create({:name => "Keno Fresemann", :email => "freezyman@aol.com", :gift => nil})
Guest.create({:name => "Kim Zumpfort", :email => "kimzumpfort@gmx.de", :gift => nil})
Guest.create({:name => "Kirsten Winter", :email => "kirsten.winter91@googlemail.com", :gift => nil})
Guest.create({:name => "Kirstin Podeschwik", :email => "Kirstin.Podeschwik@inform-ac.com", :gift => nil})
Guest.create({:name => "Kristin Hammer", :email => "kristin@allmeling.de", :gift => nil})
Guest.create({:name => "Kristina Franken", :email => "tina.franken@gmx.de", :gift => nil})
Guest.create({:name => "Kristina Lauermann", :email => "Lunaslot@gmx.de", :gift => nil})
Guest.create({:name => "Laura Cortona Allmeling", :email => "l.cortona@gmx.ch", :gift => nil})
Guest.create({:name => "Lea Aldenhoven", :email => "lea.aldenhoven@web.de", :gift => nil})
Guest.create({:name => "Liane Linke", :email => "linke@fh-aachen.de", :gift => nil})
Guest.create({:name => "life is music - dj booking", :email => "info@life-is-music.de", :gift => nil})
Guest.create({:name => "Lina Führer", :email => "lina-kiel@gmx.de", :gift => nil})
Guest.create({:name => "Linda Daheim", :email => "Linda.S.D@web.de", :gift => nil})
Guest.create({:name => "Linda Diepenbruck", :email => "linniepuh@googlemail.com", :gift => nil})
Guest.create({:name => "Linda Lücke", :email => "lindaluecke@yahoo.com", :gift => nil})
Guest.create({:name => "Lise Dreiack", :email => "lise.dreiack@gmx.net", :gift => nil})
Guest.create({:name => "Liwen Zhu", :email => "liwenzf@googlemail.com", :gift => nil})
Guest.create({:name => "Luca Hagenah", :email => "luca.hagenah@gmail.com", :gift => nil})
Guest.create({:name => "Lucie Dammann", :email => "lucie.dammann@gmx.de", :gift => nil})
Guest.create({:name => "Lutz Blätte", :email => "reisliebhaber@gmx.de", :gift => nil})
Guest.create({:name => "Malte Wulfmeier", :email => "Malte.Wulfmeier@web.de", :gift => nil})
Guest.create({:name => "Mandy Becker", :email => "becker_mandy@yahoo.de", :gift => nil})
Guest.create({:name => "Marc Fischer", :email => "fischer@chill-out.de", :gift => nil})
Guest.create({:name => "Marc Galonska", :email => "MGalonska@web.de", :gift => nil})
Guest.create({:name => "Marco Laumen", :email => "marco.laumen@gmx.de", :gift => nil})
Guest.create({:name => "Marco Sievert", :email => "sievert@eventac.de", :gift => nil})
Guest.create({:name => "Marian Almansa Frias", :email => "maalfr_arq@hotmail.com", :gift => nil})
Guest.create({:name => "Marietta Bach", :email => "marietta_bach@gmx.de", :gift => nil})
Guest.create({:name => "Marijke Schomacker", :email => "marijke.schomacker@gmx.de", :gift => nil})
Guest.create({:name => "Mario Irrmischer", :email => "cmp-audio@gmx.de", :gift => nil})
Guest.create({:name => "Martin Dammann", :email => "martin.dammann@gmx.de", :gift => nil})
Guest.create({:name => "Martin Knorr", :email => "martin.knorr@googlemail.com", :gift => nil})
Guest.create({:name => "Martina Suchanek", :email => "martina.suchanek@gmx.de", :gift => nil})
Guest.create({:name => "Meike Skrobucha", :email => "meike.skrobucha@web.de", :gift => nil})
Guest.create({:name => "Melanie Wulfmeier", :email => "mel.wulfmeier@googlemail.com", :gift => nil})
Guest.create({:name => "Michael Knoblauch", :email => "mknoblauch@gmail.com", :gift => nil})
Guest.create({:name => "Michèle Zimmermann", :email => "michele.zimmermann@gmx.net", :gift => nil})
Guest.create({:name => "Miriam Aldenhoven", :email => "miria@gmx.net", :gift => nil})
Guest.create({:name => "Miriam Schimanke", :email => "miriamschimanke@gmail.com", :gift => nil})
Guest.create({:name => "Momy Taiheb", :email => "m.tayyab@mailcity.com", :gift => nil})
Guest.create({:name => "Nadja Hoffmann", :email => "nahoffmann@web.de", :gift => nil})
Guest.create({:name => "Nailis & Nailis", :email => "mail@nailis-design.de", :gift => nil})
Guest.create({:name => "Niko Eisenmann", :email => "buh.erschrocken@googlemail.com", :gift => nil})
Guest.create({:name => "Nils Führer", :email => "nils.fuehrer@web.de", :gift => nil})
Guest.create({:name => "Nina Schroer", :email => "n.schroer@gmx.de", :gift => nil})
Guest.create({:name => "Ole Nordhoff", :email => "OleNordhoff@gmx.de", :gift => nil})
Guest.create({:name => "Paco Alcaide Tubío", :email => "palcaide@t2v.com", :gift => nil})
Guest.create({:name => "Pascal Dietrich", :email => "pdi@akustik.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Patrik Vogtel", :email => "Vogtel@hitnet.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Paul Arndt", :email => "mail@printspaul.com", :gift => nil})
Guest.create({:name => "Petra Niggemeier", :email => "petra.niggemeier@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Petra Theiß", :email => "Pet@theiss-multimedia.de", :gift => nil})
Guest.create({:name => "Pitt Wagner", :email => "pitt.wagner@googlemail.com", :gift => nil})
Guest.create({:name => "Rahel Schmitz", :email => "rahel.schmitz@huschmi.de", :gift => nil})
Guest.create({:name => "Ralf Esser", :email => "RalfEsser@gmx.de", :gift => nil})
Guest.create({:name => "Ralf Schoenemann", :email => "ralf.schoenemann@me.com", :gift => nil})
Guest.create({:name => "Rami Aker", :email => "ramiaker@gmail.com", :gift => nil})
Guest.create({:name => "Raul Bussot", :email => "Raul@raulbussot.com", :gift => nil})
Guest.create({:name => "René Kocyan", :email => "rene.kocyan@googlemail.com", :gift => nil})
Guest.create({:name => "Renzo Vitale", :email => "renzo.vitale@googlemail.com", :gift => nil})
Guest.create({:name => "Roger Uhle", :email => "uhle@fh-aachen.de", :gift => nil})
Guest.create({:name => "Ruth Bedbur", :email => "Bedbur@fh-aachen.de", :gift => nil})
Guest.create({:name => "Ruth Eisenmann", :email => "ruth.eisenmann@duesseldorf.de", :gift => nil})
Guest.create({:name => "Sabrina Sauren", :email => "SabrinaSauren@gmx.de", :gift => nil})
Guest.create({:name => "Sandra Schoenemann", :email => "sandra.schoenemann@me.com", :gift => nil})
Guest.create({:name => "Sarah Hollfeld", :email => "saholli@aol.com", :gift => nil})
Guest.create({:name => "Sascha Lutz Zimmermann", :email => "lutzman@gmx.de", :gift => nil})
Guest.create({:name => "Sebastian Krämer", :email => "sk@dotob.de", :gift => nil})
Guest.create({:name => "Sebastian Kuhlmann", :email => "Sebastian.Kuhlmann@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Sebastian Theiss", :email => "theiss@iot.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Silvia Fröhlig", :email => "Silvie83@gmx.de", :gift => nil})
Guest.create({:name => "Simon Frischemeier", :email => "frische@gmail.com", :gift => nil})
Guest.create({:name => "Simon Olk", :email => "simon.olk@gmx.de", :gift => nil})
Guest.create({:name => "Simone Gatzen", :email => "make-up@simonegatzen.de", :gift => nil})
Guest.create({:name => "Stefanie Erkeling", :email => "mail@stefanie-erkeling.de", :gift => nil})
Guest.create({:name => "Stefanie Speckgens", :email => "s.speckgens@web.de", :gift => nil})
Guest.create({:name => "Steffi Meiendresch", :email => "steffi.meiendresch@googlemail.com", :gift => nil})
Guest.create({:name => "Stephan Adrian", :email => "mail@stephan-adrian.de", :gift => nil})
Guest.create({:name => "Stephan Polte", :email => "stephan.polte@gmx.de", :gift => nil})
Guest.create({:name => "Stephanie Houis", :email => "steffihouis@gmx.de", :gift => nil})
Guest.create({:name => "Susanne Hellebrand", :email => "hellebrand@fh-aachen.de", :gift => nil})
Guest.create({:name => "Sven Schumacher", :email => "mail@svenschumacher.com", :gift => nil})
Guest.create({:name => "Tamara Münstermann", :email => "mana_muensi@yahoo.de", :gift => nil})
Guest.create({:name => "Thilo Vogel", :email => "thilo.vogel@gmail.com", :gift => nil})
Guest.create({:name => "Thomas Schermer", :email => "thomas_schermer@gmx.de", :gift => nil})
Guest.create({:name => "Thompson  Eleonor", :email => "Eleonor.Thompson@zhv.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Tim Legler", :email => "tim.legler@googlemail.com", :gift => nil})
Guest.create({:name => "Timm Dapper", :email => "timm.dapper@td-grafik.de", :gift => nil})
Guest.create({:name => "Tjalf Gokert", :email => "tjalf01@yahoo.de", :gift => nil})
Guest.create({:name => "Tobias Frischemeier", :email => "tobias.frischemeier@t-online.de", :gift => nil})
Guest.create({:name => "Uwe Heinrichs", :email => "dr.uwe.heinrichs@gmail.com", :gift => nil})
Guest.create({:name => "Vasilis Vasiliou", :email => "vasi23@gmx.de", :gift => nil})
Guest.create({:name => "Vera Schlensker", :email => "Vera.Schlensker@gmx.de", :gift => nil})
Guest.create({:name => "Victoria Busch", :email => "buschvictoria@gmail.com", :gift => nil})
Guest.create({:name => "Viviane Fröhlich", :email => "summer.dream@web.de", :gift => nil})
Guest.create({:name => "Wilhelm Leisten-Lorent", :email => "photo@wilhelm-leisten.de", :gift => nil})
Guest.create({:name => "Alex van Winckel", :email => "alex_vw@web.de", :gift => nil})
Guest.create({:name => "Andrea Nordhoff", :email => "andrea@textdenker.de", :gift => nil})
Guest.create({:name => "Felix Allmendinger", :email => "Felix.Allmendinger@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Benjamin Buch", :email => "benni.buch@gmx.de", :gift => nil})
Guest.create({:name => "Christian Gass", :email => "Christian.Gass@googlemail.com", :gift => nil})
Guest.create({:name => "Christian Vedder", :email => "mail@christianvedder.de", :gift => nil})
Guest.create({:name => "Christina Heinrichs", :email => "c.heinrichs@die-heinrichs.net", :gift => nil})
Guest.create({:name => "Christoph Brune", :email => "ch.brune@googlemail.com", :gift => nil})
Guest.create({:name => "Christoph Hammer", :email => "christoph.hammer@gmx.net", :gift => nil})
Guest.create({:name => "COKRON Innovations | Björn Großmann", :email => "bg@cokron.de", :gift => nil})
Guest.create({:name => "Dennis Könißer", :email => "dennis.koenisser@gmail.com", :gift => nil})
Guest.create({:name => "Björn Eberhardt", :email => "mail@ibjorn.de", :gift => nil})
Guest.create({:name => "Fabian Koebrügge", :email => "f.koebrugge@googlemail.com", :gift => nil})
Guest.create({:name => "judith fothen", :email => "judith.fothen@gmail.com", :gift => nil})
Guest.create({:name => "Guido Holz", :email => "guido@sportograf.de", :gift => nil})
Guest.create({:name => "Uwe Heinrichs", :email => "uwe@die-heinrichs.net", :gift => nil})
Guest.create({:name => "Ilka Reuter", :email => "winnitwo@gmail.com", :gift => nil})
Guest.create({:name => "Jan Karger", :email => "punkerat76@googlemail.com", :gift => nil})
Guest.create({:name => "Katja Krämer", :email => "katja.kraemer@gmail.com", :gift => nil})
Guest.create({:name => "Martin Knorr", :email => "martin.knorr@googlemail.com", :gift => nil})
Guest.create({:name => "jenni kielas", :email => "jenni.kielas@gmail.com", :gift => nil})
Guest.create({:name => "Tim Legler", :email => "tim.legler@googlemail.com", :gift => nil})
Guest.create({:name => "Kai Röller", :email => "kai@aquaplan.de", :gift => nil})
Guest.create({:name => "Katharina Krämer", :email => "lieblingsbiene@googlemail.com", :gift => nil})
Guest.create({:name => "Linda Diepenbruck", :email => "linniepuh@googlemail.com", :gift => nil})
Guest.create({:name => "Ole Nordhoff", :email => "OleNordhoff@gmx.de", :gift => nil})
Guest.create({:name => "Kirstin Podeschwik", :email => "Kirstin.Podeschwik@inform-ac.com", :gift => nil})
Guest.create({:name => "Dirk Sorges", :email => "Dirk.Sorges@inform-ac.com", :gift => nil})
Guest.create({:name => "Miriam Schimanke", :email => "miriamschimanke@googlemail.com", :gift => nil})
Guest.create({:name => "TheissSebastian", :email => "theiss@iot.rwth-aachen.de", :gift => nil})
Guest.create({:name => "Petra Theiß", :email => "petra.theiss@weiss-steuern.de", :gift => nil})
Guest.create({:name => "Renzo Vitale", :email => "renzo.vitale@googlemail.com", :gift => nil})
Guest.create({:name => "Jochen Wilms", :email => "jochen@ausfuehrer.de", :gift => nil})
Guest.create({:name => "Randi Zimmermann", :email => "Randi.Zimmermann@inform-ac.com", :gift => nil})
Guest.create({:name => "Ralf Schoenemann", :email => "ralf@formdenker.de", :gift => nil})
Guest.create({:name => "Sandra", :email => "sandra.damm@gmail.com", :gift => nil})
Guest.create({:name => "Thilo Vogel", :email => "photos@lichtographie.de", :gift => nil})
Guest.create({:name => "Max Heidbüchel", :email => "maxx@riesentyp.de", :gift => nil})
Guest.create({:name => "Anja Späker", :email => "aranja@web.de", :gift => nil})

Guest.create({:name => "Julia Harnacke", :email => "harnacke_julia@yahoo.de", :gift => nil})
Guest.create({:name => "Kim Selle", :email => "kim.selle@gmx.de", :gift => nil})
Guest.create({:name => "Marc Flegel", :email => "marcflegel@gmx.de", :gift => nil})
Guest.create({:name => "Nina Koebrügge", :email => "ninak_sta@hotmail.com", :gift => nil})
Guest.create({:name => "Vera Johanna Offermanns", :email => "Vera.Offermanns@rwth-aachen.de", :gift => nil})
Guest.create({:name => "Anne-Christin Boll", :email => "A-C.Boll@gmx.net", :gift => nil})
Guest.create({:name => "Matthias Buhl", :email => "m.buhl@dokom.net", :gift => nil})
Guest.create({:name => "Nils Hammesfahr", :email => "n.hammesfahr@web.de", :gift => nil})
Guest.create({:name => "Till klein Rudack", :email => "till.rudack@web.de", :gift => nil})
Guest.create({:name => "till groß hellenkamp", :email => "tillhellenkamp@gmx.de", :gift => nil})
Guest.create({:name => "Matthias Weckelmann", :email => "m.weckelmann@gmx.de", :gift => nil})
Guest.create({:name => "Ellen Buhl", :email => "ellen.buhl@gmx.de", :gift => nil})
Guest.create({:name => "Katrin Buhl", :email => "katrin.buhl@gmx.net", :gift => nil})
Guest.create({:name => "Jule Kötter", :email => "jule.koetter@googlemail.com", :gift => nil})

# gifts
Gift.create({:name => "Kasten Bier", :price => 15})
Gift.create({:name => "DJ-Anteil", :price => 10})
Gift.create({:name => "DJ-Anteil", :price => 15})
Gift.create({:name => "DJ-Anteil", :price => 20})
Gift.create({:name => "Caipirinha", :price => 10})
Gift.create({:name => "Wodka", :price => 10})
