#Guest.create!({:name => "Lise Dreiack", :email => "lise.dreiack@gmx.net", :gift => nil})
#Guest.create!({:name => "Ruth Roentgen", :email => "ruth.roentgen@gmx.net", :gift => nil})
#Guest.create!({:name => "Verena Deege", :email => "verena.deege@gmx.de", :gift => nil})
#Guest.create!({:name => "Barbara Galli", :email => "barbarababette@hotmail.com", :gift => nil})
#Guest.create!({:name => "Daniela", :email => "Rodtheut", :email => "daniela.rodtheut@gmx.net", :gift => nil})
#Guest.create!({:name => "Emmelien Gittner", :email => "e.gittner@student.maastrichtuniversity.nl", :gift => nil})
#Guest.create!({:name => "Kristina Franken", :email => "Kristina.Franken@alsdorf.de", :gift => nil})
#Guest.create!({:name => "Julia Papenkort", :email => "julia.papenkort@gmx.de", :gift => nil})
#Guest.create!({:name => "Stephanie Haag", :email => "stephanie-t-h@web.de", :gift => nil})
#Guest.create!({:name => "Victoria Busch", :email => "vitto78@gmail.com", :gift => nil})
#Guest.create!({:name => "Els Clara Vrielynck", :email => "vrielynck@gmx.de", :gift => nil})
#Guest.create!({:name => "Selma Akkari", :email => "sakkari@pratt.edu", :gift => nil})
Guest.create!({:name => "Bianca Boekmann", :email => "bianca9486@msn.com", :gift => nil})
#Guest.create!({:name => "Anna Hecker", :email => "annahecker@gmx.de", :gift => nil})
#Guest.create!({:name => "Doro Behler", :email => "doro@bassyst.de", :gift => nil})
Guest.create!({:name => "Daniela Ewers", :email => "daniela.ewers@gmail.com", :gift => nil})
Guest.create!({:name => "Fanny Eberhard Wallace", :email => "fanfanlatulipe_03@hotmail.com", :gift => nil})
Guest.create!({:name => "Fee Denise Horstmann", :email => "petitenis@hotmail.com", :gift => nil})
Guest.create!({:name => "Julia Hammer", :email => "ju-hammer@web.de", :gift => nil})
Guest.create!({:name => "Leoni Stiller", :email => "leoni.stiller@web.de", :gift => nil})
#Guest.create!({:name => "Katharina Scholl", :email => "katharina.scholl@web.de", :gift => nil})
#Guest.create!({:name => "Maria Roentgen", :email => "maria.roentgen@gmx.net", :gift => nil})
Guest.create!({:name => "Sabrina Sauren", :email => "SabrinaSauren@gmx.de", :gift => nil})
#Guest.create!({:name => "Julia Deege", :email => "juls0n@hotmail.de", :gift => nil})
#Guest.create!({:name => "Sonja Dittrich", :email => "sonjadittrich@gmx.de", :gift => nil})
#Guest.create!({:name => "Cathrin Weich", :email => "cathrin.weich@gmx.de", :gift => nil})
Guest.create!({:name => "Luca Hagenah", :email => "luca.hagenah@gmail.com", :gift => nil})
Guest.create!({:name => "Alessandro Vitale", :email => "alessandrovitale@libero.it", :gift => nil})
Guest.create!({:name => "Alessandro Farinelli", :email => "drone1978@hotmail.com", :gift => nil})
Guest.create!({:name => "Adam Thompson", :email => "adam.jacob.thompson@gmail.com", :gift => nil})
Guest.create!({:name => "Roberto De Mitri", :email => "rdemitri@hotmail.com", :gift => nil})
